import { describe, expect, it } from 'vitest';
import { blackScholesPrice, type BsmParams } from './black-scholes.js';
import { checkPutCallParity } from './parity.js';

const reference: BsmParams = { S: 100, K: 100, r: 0.05, sigma: 0.2, T: 1 };

describe('checkPutCallParity', () => {
  it('holds for prices generated by the BSM formula itself', () => {
    const callPrice = blackScholesPrice('call', reference);
    const putPrice = blackScholesPrice('put', reference);
    const result = checkPutCallParity({ callPrice, putPrice, S: 100, K: 100, r: 0.05, T: 1 });
    expect(result.holds).toBe(true);
    expect(result.difference).toBeCloseTo(0, 8);
  });

  it('detects a violation when prices are inconsistent', () => {
    const result = checkPutCallParity({
      callPrice: 10.45,
      putPrice: 20, // deliberately wrong
      S: 100,
      K: 100,
      r: 0.05,
      T: 1,
    });
    expect(result.holds).toBe(false);
    expect(Math.abs(result.difference)).toBeGreaterThan(1);
  });

  it('accounts for a continuous dividend yield', () => {
    const params: BsmParams = { ...reference, q: 0.03 };
    const callPrice = blackScholesPrice('call', params);
    const putPrice = blackScholesPrice('put', params);
    const result = checkPutCallParity({ callPrice, putPrice, S: 100, K: 100, r: 0.05, T: 1, q: 0.03 });
    expect(result.holds).toBe(true);
  });
});
